# Generated by Django 3.2.8 on 2021-12-03 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_ramos_usuario_foto_ramo'),
    ]

    operations = [
        migrations.CreateModel(
            name='apuntes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo_apunte', models.CharField(max_length=200)),
                ('informacion_apunte', models.CharField(max_length=200)),
                ('archivo', models.FileField(upload_to='apuntes/archivos/')),
            ],
        ),
    ]
